version: '3.8'

services:
  mockserver:
    build: .
    container_name: mockserver_v1
    ports:
      - "5000:5000" 
    volumes:
      - ./example:/example
    restart: unless-stopped
    command: ["start", "--config", "/example/mockserver.yaml"]